# Generated by Django 5.1.5 on 2025-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_tags_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Title of the blog post', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(help_text='Email of the comment', max_length=254),
        ),
    ]
