# Generated by Django 5.1.5 on 2025-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0003_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(help_text='Client e.g', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(help_text='Project type e.g', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='service',
            field=models.CharField(help_text='Service e.g,', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(help_text='Year e.g', max_length=4),
        ),
    ]
